blank_issues_enabled: false
contact_links:
  - name: General Questions or Chat
    url: https://github.com/jamescockerham/Cockerh.am/discussions
    about: Use Discussions for questions â€” issues are only for adding data to the site.